### ISSUE TITLE
Wrong charset

### ISSUE THREAD

**Issue by D1mon** [episage/next-page-chrome-extension#1]
You need to add the option to force a change of encoding. And another question is the correct xpath :? Is it possible to return 2 tags?
`//...//tr[@class="row1" or @class="row2"]`
Only the 2nd page is loaded and that's it.

Here is an example of an incorrect encoding request.
![charset](https://user-images.githubusercontent.com/3872485/55674646-fc83ba80-58bf-11e9-8805-6d70be13676f.png)

**Comment by episage** [comment]
Hi @D1mon ! Thanks for the first issue. 

`//...//tr[@class="row1" or @class="row2"]` will take the first one found.

As for the charset, can you post website URL you are trying to pagerize so I can try it myself?

**Comment by D1mon** [comment]
check gmail

**Comment by episage** [comment]
Hi @D1mon , I tried to fix the issue with characters but I can't. I don't know what to do to be honest with you.
Here are my rules for NextPage Chrome extension:
```
url ^https://nnm-club.me/forum/
pe //table[@class='forumline']/tbody/tr[@class='row1' or @class='row2']
nl //span[@class='nav']/a[text()='След.']

```

Any ideas?

**Comment by D1mon** [comment]
I don’t know how the extension works, but I can assume that when the end of the page is reached, the plugin looks for the “Next page” button. And as if pressing on it. But the page does not change and repeated pressing does not work.
It seems to me that you need to do this:
1) make a template for changing values ​​in this case viewtopic.php?t=<topic_id>&start={$NUM}
2) NUM - changes by 15 (0,15,30,45, ...)
3) if on the page you can find out the last page (for example: 90)
4) add to template: lastPage | lp <xpath>  //(lastPage = 90)
5) when reaching the end of the page - make a request viewtopic.php?t=<topic_id>&start=30

As for the encoding, I'm not exactly sure, but we need to add the header to the request: (Content-Type: ... ;charset=windows-1251) in this case, but in general it is necessary for each site to recognize its encoding and to make requests with this encoding.

**Comment by episage** [comment]
Hi @D1mon , you mentioned a lot of topis so I will handle them one by one:
`I don’t know how the extension works,` -  you can look it up here: `https://github.com/episage/next-page-chrome-extension/blob/master/src/contentScript.js`, especially `window.addEventListener('load'`

`I can assume that when the end of the page is reached, the plugin looks for the “Next page” button` - yes `https://github.com/episage/next-page-chrome-extension/blob/master/src/contentScript.js#L27`

` And as if pressing on it. But the page does not change and repeated pressing does not work.` - Can you write this sentence in more correct English? I can't understand you. Also, it works for me, except for wrong encoding.

```
It seems to me that you need to do this:

make a template for changing values ​​in this case viewtopic.php?t=<topic_id>&start={$NUM}
NUM - changes by 15 (0,15,30,45, ...)
if on the page you can find out the last page (for example: 90)
add to template: lastPage | lp //(lastPage = 90)
when reaching the end of the page - make a request viewtopic.php?t=<topic_id>&start=30
```
This is more-or-less what is happening under the hood. What do you mean by saying that `I need to do this:`?

```
As for the encoding, I'm not exactly sure, but we need to add the header to the request: (Content-Type: ... ;charset=windows-1251) in this case, but in general it is necessary for each site to recognize its encoding and to make requests with this encoding.
```
I'm not sure either. I think sending `charset=windows-1251` won't work since this issue is related to to page rendering.

**Comment by D1mon** [comment]
`I don’t know how the extension works,`
I don't know JavaScript

`Can you write this sentence in more correct English?`
not. Google translation

`I'm not sure either. I think sending charset=windows-1251 won't work since this issue is related to to page rendering.`
may be

We will wait until there are knowledgeable people.

**Comment by episage** [comment]
I fixed this in v1.1.1. Published and pending review in Chrome Web Store.

**Comment by D1mon** [comment]
The topic is not closed because the error remains.
https://www.dropbox.com/s/ej76jkf5hnhw61x/next-page-err.mkv?dl=0

**Comment by episage** [comment]
Google updated the extension in the store. Try it now @D1mon . V1.1.1 has the issue resolved

**Comment by D1mon** [comment]
Yes. It WORKS!!! :)
